### ISSUE TITLE
Getting multiple responses for Ticker Polgon IO

### ISSUE THREAD

**Issue by mohdshoebali565** [polygon-io/client-js#106]
Hi Team , We are trying to consume ticker polygon IO API and we are passing the expected parameters (see attached), but the request url / response parameters seems to be very different

Please see the expected output in the below mentioned url 
https://polygon.io/docs/stocks/get_v3_reference_tickers

Please find the output  getting  in the attached screenshot ( we are consuming the same API which was provided in the above url but the response is different)

Please do the needful

![image](https://user-images.githubusercontent.com/117293491/199524853-e4596b2d-e84a-4e84-855b-c40e5fafb4a1.png)

<img width="574" alt="PolygonIOTicker" src="https://user-images.githubusercontent.com/117293491/199523220-aac16798-f1e9-4219-9685-e1e3602b0912.PNG">

**Comment by mohdshoebali565** [comment]
Can you please update on the ticket raised .. We are not able to proceed further ..its impacting our  productivity

**Comment by yehudabortz** [comment]
@mohdshoebali565 Sorry for the delayed response from the team. Are you still encountering an issue here?

**Comment by timetraveler328** [comment]
@mohdshoebali565 the first parameter passed to reference.tickers should be an object with all query parameters being passed to the endpoint (instead of passing them all to the function as individual parameters).

Your code should look like this instead `await reference.tickers({ ticker, type, market, exchange, cik, date, active })` where each query element is an object key.  In this case, you're passing an empty object as the first parameter, so no filters are included and it's returning all tickers.
