### ISSUE TITLE
Unhandled promise rejection when connection refused

### ISSUE THREAD

**Issue by jdconley** [polygon-io/client-js#131]
Version: 6.2.0

I see an unhandled promise rejection when there is a connection refused error. This error isn't reaching my code that is making the call. 

```ts
    const polygonSummaries = await this.polygonClient.stocks.summaries(
      {
        'ticker.any_of': tickerSymbols.join(','),
      },
      edgeHeaders,
    );
```

I see this error in the logs when we run up against a rate limit. I was testing to see what the capacity might be like. That is fine but I need to be able to handle the error properly and it gets lost to the global error handler because it's an unhandled promise rejection. We are running Datadog tracing so that's why you see it in the error handling stack.

```
FetchError: request to https://api.polygon.io/v1/summaries?apiKey=***REDACTED***&ticker.any_of=AAPL%2CAMZN%2CGOOG%2CMETA%2CTSLA failed, reason: connect ECONNREFUSED 198.44.194.22:443
    at ClientRequest.<anonymous> (/backend/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.req.emit (/backend/node_modules/dd-trace/packages/datadog-instrumentations/src/http/client.js:95:23)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:525:35)
    at TLSSocket.emit (/backend/node_modules/dd-trace/packages/datadog-instrumentations/src/net.js:61:25)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by timetraveler328** [comment]
Hey @jdconley, thanks for filing this issue.

I think I understand the scenario, but let me run it by you just to be sure: 

When fetch encounters a network error, it rejects the promise instead of resolving with a non-okay status code. Our fetch call wasn't in a try/catch, so whenever you encountered a network error, the global unhandled rejection event was being triggered and showing up in your logs. I've created a PR to catch the promise rejection and then explicitly throw a new error. If this all sounds right, I'll get a patch out for you. 

I can go back and patch version 6 as well if you'd like, or if you'd like to upgrade to version 7, there's just a slight change to the format of the second parameter in your example: from `edgeHeaders` to `{ headers: edgeHeaders }`

**Comment by jdconley** [comment]
> If this all sounds right, I'll get a patch out for you.

That does sound about right, thanks. I just want to be able to know when an exception occurs so it can be handled. That could be through return codes or re-throwing. Up to your interface design. I think an exception makes sense in this case. 

> I can go back and patch version 6 as well if you'd like, or if you'd like to upgrade to version 7, there's just a slight change to the format of the second parameter in your example: from `edgeHeaders` to `{ headers: edgeHeaders }`

I tried the new library but the breaking change with the module format made it difficult to upgrade. I had hundreds of compiler errors to fix. It's probably going to take hours to migrate our project to the new format so I didn't want to bite that off. I would prefer a patch to 6.x.

Thanks!
