### ISSUE TITLE
Add browser support

### ISSUE THREAD

**Issue by jaydenwindle** [polygon-io/client-js#8]
This library currently only supports Node.js, due to it's use of `https`, `ws` and `querystring`. 

It would be awesome if this library could be used in a browser environment as well.

**Comment by bassochette** [comment]
The issue with using this client in a browser is that you would give your API KEY publicly.

We'd a secret/publishable key mechanism to it in a browser.

**Comment by jaydenwindle** [comment]
Correct, this does require storing the API key on the client. However, since the Polygon API is read-only, this API key is essentially functioning as a publishable key already. As far as I can tell the API key is only used to match requests to a polygon account, making it similar to a client ID.

A secret / publishable key would be needed once the API supports authenticated write operations, and could be added then. The only attack vectors with a stolen key right now are abusing rate-limits and / or bypassing the paid subscription.

**Comment by mikestead** [comment]
Was just looking into this and had the same question.

To open this up to a browser would be a little confusing, as the key on the platform page specifically states it's a secret, so passing it in browser context would indeed violate that.

The same key is used by all of your other server side SDKs so this would usually be treated as a secret (would be good to call this a Node.js library if secrets are involved).

Another small point, I don't think you get access to the API until you subscribe with a credit card, so it is more than an API key at that point, no matter how you physically deal with it during API access. Otherwise you open a simple back door to API access under someone else's account.

Just my 2c, keep up the good work.
