### ISSUE TITLE
Invalid query string when using object parameters in IPolygonQuery

### ISSUE THREAD

**Issue by randomf** [polygon-io/client-js#89]
When object parameter is used in `IPolygonQuery` the API request fails. For instance for
```
    const query: IPolygonQuery = {
      timestamp: {
        lte: '2022-05-12',
      },
      order: "desc",
      limit: 5,
    };
```
as a query parameter of `polygonClient.stocks.trades()`, following string is produced by `query-string`'s `stringify` function: `limit=5&order=desc&timestamp=%5Bobject%20Object%5D`. Encoding objects is not supported by `stringify`. 

See https://github.com/polygon-io/client-js/blob/master/src/rest/transport/request.ts

**Comment by teambailey** [comment]
Hi @randomf!

Thank you for reporting this issue and apologies for the delay in resolution. The issue was that the `IPolygonQuery` included an option for `object` to be an acceptable type value for the query object's entry values. That should not be the case due to the support limitation of the `stringify` package as you stated.

The latest v6.0.1 release corrects that problem. You're query above will require a refactor to look like this due to the change:

```
const query: IPolygonQuery = {
  "timestamp.lte": '2022-05-12'},
  order: "desc",
  limit: 5
};
```

Thank you again for the report and interest in Polygon.io!
